#!/bin/sh
# openclaw-dns entrypoint: generate /etc/dnsmasq.conf from /etc/whitelist.txt,
# then exec dnsmasq. Supports --print-only for tests (prints generated config
# to stdout without writing or starting dnsmasq).
set -eu

WHITELIST_FILE="${WHITELIST_FILE:-/etc/whitelist.txt}"
OUTPUT_FILE="/etc/dnsmasq.conf"
PRINT_ONLY=0

for arg in "$@"; do
    case "$arg" in
        --print-only) PRINT_ONLY=1 ;;
    esac
done

if [ ! -r "$WHITELIST_FILE" ]; then
    echo "[openclaw-dns] ERROR: whitelist file not readable: $WHITELIST_FILE" >&2
    exit 1
fi

generate() {
    cat <<'STATIC_HEADER'
# Auto-generated by openclaw-dns entrypoint.sh from /etc/whitelist.txt
# DO NOT EDIT -- edit config/whitelist.txt and restart the container

listen-address=172.24.0.253
bind-interfaces
user=root

# Block unlisted domains (return NXDOMAIN)
address=/#/

# Docker container names -> Docker embedded DNS
server=/openclaw-bridge/127.0.0.11
server=/openclaw-sniproxy/127.0.0.11
server=/openclaw-ingress/127.0.0.11
server=/openclaw-litellm/127.0.0.11
server=/openclaw-agent/127.0.0.11
server=/openclaw-dns/127.0.0.11

# Don't read /etc/resolv.conf
no-resolv

# Logging
log-queries

# --- Whitelisted external domains (from /etc/whitelist.txt) ---
STATIC_HEADER

    tr -d '\r' < "$WHITELIST_FILE" \
        | sed -e 's/#.*$//' -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' \
        | awk 'NF > 0 && /^[a-zA-Z0-9.-]+$/ { print "server=/" $1 "/8.8.8.8" }'
}

if [ "$PRINT_ONLY" = "1" ]; then
    generate
    exit 0
fi

generate > "$OUTPUT_FILE"
exec dnsmasq -k --conf-file="$OUTPUT_FILE"
