#!/bin/sh
# openclaw-sniproxy entrypoint: generate /etc/nginx/nginx.conf from
# /etc/whitelist.txt, then exec nginx. Supports --print-only for tests.
set -eu

WHITELIST_FILE="${WHITELIST_FILE:-/etc/whitelist.txt}"
OUTPUT_FILE="/etc/nginx/nginx.conf"
PRINT_ONLY=0

for arg in "$@"; do
    case "$arg" in
        --print-only) PRINT_ONLY=1 ;;
    esac
done

if [ -d "$WHITELIST_FILE" ]; then
    echo "[openclaw-sniproxy] ERROR: whitelist is a directory, not a file." >&2
    echo "[openclaw-sniproxy] This is caused by a Docker Desktop bind-mount bug (internal Compose CLI path translation failure)." >&2
    echo "[openclaw-sniproxy] Fix: docker compose -f c:/LLM/judgeclaw/docker-compose.yml up -d --force-recreate openclaw-sniproxy" >&2
    exit 1
fi
if [ ! -r "$WHITELIST_FILE" ]; then
    echo "[openclaw-sniproxy] ERROR: whitelist file not readable: $WHITELIST_FILE" >&2
    exit 1
fi

generate() {
    cat <<'STATIC_HEADER'
# Auto-generated by openclaw-sniproxy entrypoint.sh from /etc/whitelist.txt
# DO NOT EDIT -- edit config/whitelist.txt and restart the container

error_log /var/log/nginx/error.log warn;

events {
    worker_connections 128;
}

stream {
    resolver 127.0.0.11 valid=300s ipv6=off;
    resolver_timeout 5s;

    log_format snilog '$remote_addr [$time_local] '
                      'SNI=$ssl_preread_server_name '
                      'upstream=$upstream '
                      'status=$status '
                      'bytes_sent=$bytes_sent bytes_received=$bytes_received '
                      'session_time=$session_time';

    access_log /var/log/nginx/sni_access.log snilog;

    map $ssl_preread_server_name $upstream {
        default                127.0.0.1:1;
STATIC_HEADER

    tr -d '\r' < "$WHITELIST_FILE" \
        | sed -e 's/#.*$//' -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' \
        | awk 'NF > 0 && /^[a-zA-Z0-9.-]+$/ { printf "        %s %s:443;\n", $1, $1 }'

    cat <<'STATIC_FOOTER'
    }

    server {
        listen 443;
        ssl_preread on;
        proxy_pass $upstream;
        proxy_connect_timeout 5s;
        proxy_timeout 30s;
    }
}
STATIC_FOOTER
}

if [ "$PRINT_ONLY" = "1" ]; then
    generate
    exit 0
fi

generate > "$OUTPUT_FILE"
exec nginx -g 'daemon off;'
