acl whitelist dstdomain "/etc/squid/whitelist.txt"
acl SSL_ports port 443
acl CONNECT method CONNECT

http_access allow CONNECT whitelist
http_access allow whitelist
http_access deny all

http_port 3128
